### ISSUE TITLE
키위톡의 보이스톡, 페이스톡 프로토콜... 카카오톡과 동일한가요?

### ISSUE THREAD

**Issue by MingiHongHub** [KiwiTalk/KiwiTalk#1026]
안녕하세요! 제가 해외거주중인데 카카오톡을 쓰면서 한국에 계신 부모님과 보이스톡이나 페이스톡을할때 자꾸 끈김현상이 발생해서 그 버그를 좀 개선해보려고 카카오톡 소스코드를 찾는중에 키위톡에 관심이 가게 되었습니다. 혹시 키위톡에서 보이스톡이나 페이스톡을 사용할때 사용되는 프로토콜이 카카오톡에 사용되는 프로토콜과 같다면은 그 버그를 이 키위톡에서 잡으면 될것같다는 아이디어가 생겼는데, 키위톡에 같은 프로토콜이 사용되나요?

버그에 대해 정확히 말하자면은 제가 부모님께 전화를 드리면 자주 끈김현상이 발생하지만, 부모님께서 한국에서 저한테 전화를 주면은 끈김현상이 발생하지 않더라고요. 이것엔 꼭 무슨이유가 있을것 같은데 이 키위톡 프로젝트를 통해서 이점이 개선됬으면 좋겠

**Comment by BraINstinct0** [comment]
카카오톡은 오픈소스 프로젝트가 아니며 상용 소프트웨어인 관계로, 소스코드가 공개될 가능성이 없다고 보시면 됩니다. 프로토콜 부분은 알 수 없으나 현재 제공해주신 정보만으로 유의미한 이야기가 가능할 지 모르겠습니다.
* 저는 키위톡 팀과 무관한 제 3자이니, 정확한 답변은 개발진에게 듣는 것이 좋을 것입니다.

**Comment by RanolP** [comment]
동일하다고 확답드리기는 어려울 듯 합니다. 카카오톡은 실시간으로 개선되는 소프트웨어이며, KiwiTalk은 아직 MVP 개발을 위한 첫 삽을 뜨고 있는 단계입니다. 보이스톡 등의 복잡한 기능은 개발 후순위에 있으며, 관련 개발 진척 사항을 빠르게 알고 싶으시다면, 저희 [Discord](https://discord.gg/n3eHuNuRYf)에 들어오시는 것도 나쁘지 않을 듯 합니다.

또한, 본 프로젝트의 목적은 Linux를 지원하지 않는 카카오톡 대신 대안 구현체를 만드는 것이기 때문에 개선을 약속하기에 어려운 점 양해 부탁드립니다.

마지막으로, 본 프로젝트의 이슈는 당분간 MVP 개발과 관련 있는 이슈만을 남길 예정이오니, 이슈를 닫도록 하겠습니다.
