### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by dayo05** [KiwiTalk/KiwiTalk#1029]
발현은 클론 이후 npm install, npm run start를 통하여 진행하였으며, 
Critical dependency: the request of a dependency is an expression
이것의 발현 이후 이미지 전체가 정상적으로 불러오지 못하는 오류가 이어서 발생하였습니다.

아마 제가 npm을 개발 목적으로 사용하지 않아서 무언가 실수가 있을꺼 같기도 하지만... 일단 올려봅니다.

환경은 Arch Linux의 커널 5.17.0 바닐라이며, KDE구동중입니다.

**Comment by RanolP** [comment]
#1171 에서 코드베이스를 전면 개편해 더는 유효하지 않은 문제로 추정됩니다. 만약 업그레이드 이후에도 여전히 문제가 있을 경우 코멘트를 추가로 달아주세요.
