### ISSUE TITLE
README의 UI Mockup페이지에 접근되지 않습니다.

### ISSUE THREAD

**Issue by tilto0822** [KiwiTalk/KiwiTalk#1195]
README.md에 표시되어 있는 [KiwiTalk UI Mockup](https://www.figma.com/file/4Z6MR3oZK5iSvzyvvuT4DO/KiwiTalk-UI-Mockup?node-id=0%3A1) 에 접속을 시도하면 아래와 같은 에러가 표시되며 확인할 수 없습니다.
![image](https://user-images.githubusercontent.com/56160437/188044230-99d969da-0c8c-42b9-9a49-4ff9298aff31.png)

깃허브 타임라인에서 발견하여 보고있는데 멋진 프로젝트 같습니다! 응원할게요~

**Comment by JellyBrick** [comment]
Fixed in #1212
