### ISSUE TITLE
You need to enable JavaScript to run this app

### ISSUE THREAD

**Issue by leecurrent04** [KiwiTalk/KiwiTalk#1259]
README.md 파일에 따라 설치를 하고 실행했는데, 웹화면에서 You need to enable JavaScript to run this app 문구만 나옵니다.

![Screenshot from 2022-10-04 15-28-29](https://user-images.githubusercontent.com/104289771/193749671-a462216d-ae91-4c02-aacf-6ce025eb739d.png)

https://www.upbeatcode.com/react/solved-you-need-to-enable-javascript-to-run-this-app/
에서 나오는 방법대로 해봐도 마찬가지로 오류가 나옵니다.

설치 과정에서도 오류가 있는 거 같아 파일로 첨부합니다.

[error.txt](https://github.com/KiwiTalk/KiwiTalk/files/9703268/error.txt)

**Comment by storycraft** [comment]
현재 dev브랜치에서 개발이 되고있습니다. master브랜치는 사용이 불가능합니다

**Comment by leecurrent04** [comment]
dev 브랜치에서 실행했는데도 같은 오류가 납니다.
You need to enable JavaScript to run this app

![Screenshot from 2022-10-04 21-04-46](https://user-images.githubusercontent.com/104289771/193815003-f30f0376-e57d-49d6-98e6-92c08019ed52.png)

**Comment by storycraft** [comment]
아직 보이는 것이 없기때문에 아무것도 안뜨는 것이 맞습니다

**Comment by leecurrent04** [comment]
아 그렇군요. 감사합니다
