### ISSUE TITLE
Build done, but Failed to Run (dev branch)

### ISSUE THREAD

**Issue by BraINstinct0** [KiwiTalk/KiwiTalk#1269]
Using the [current dev branch](https://github.com/KiwiTalk/KiwiTalk/tree/dev), the build & run instructions does not work properly.
Environment: (dockerized) Ubuntu 20.04, Nodejs 14/16/18 (all show identical behavior)
on `yarn`:
```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > styled-components@5.3.6" has unmet peer dependency "react-is@>= 16.8.0".
warning "@storybook/addon-actions > react-inspector@5.1.1" has incorrect peer dependency "react@^16.8.4 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @mdx-js/react@1.6.22" has incorrect peer dependency "react@^16.13.1 || ^17.0.0".
warning " > babel-loader@8.2.5" has unmet peer dependency "webpack@>=2".
warning " > @storybook/react@6.5.12" has unmet peer dependency "require-from-string@^2.0.2".
warning "@storybook/react > react-element-to-jsx-string@14.3.4" has incorrect peer dependency "react@^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1".
warning "@storybook/react > react-element-to-jsx-string@14.3.4" has incorrect peer dependency "react-dom@^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1".
[4/4] Building fresh packages...
Done in 98.58s.
```
Then on `yarn dev`:
yarn run v1.22.19
$ tauri dev
     Running BeforeDevCommand (`npm run frontend:dev`)

> kiwi-talk@0.1.0 frontend:dev
> vite

  VITE v3.1.6  ready in 534 ms

  ���  Local:   http://localhost:5173/
  ���  Network: use --host to expose
       Error failed to get project out directory: failed to get cargo metadata: No such file or directory (os error 2)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by storycraft** [comment]
It requires Rust build tools (rustup, cargo) to build.

Install Rust here https://www.rust-lang.org/tools/install
