### ISSUE TITLE
Mac에서 설치했는데, 빈 화면만 나옵니다. ("Need to enable Javascript" error)

### ISSUE THREAD

**Issue by invu7** [KiwiTalk/KiwiTalk#1276]
안녕하세요?

Mac에서 KiwiTalk을 설치했는데,
설치 과정에서 여러가지 우여곡절 끝에 (yarn 설치부터, node upgrade, rustup, cargo 설치, 나중에 node 다시 downgrade 등..)
일단 설치는 다 된 것 같고, yarn dev하면 kiwi-talk 앱과 화면은 뜨는데, 
아무 것도 없는 하얀 빈 화면만 보입니다.

우클릭해서 "Inspect Element" 해서 보면, HTML code가 보이는데,
body 부분에 아래와 같이 나오는군요.
이런 경우 어떻게 해결해야 하나요? ㅠ

```
<body>
<noscript>You need to enable JavaScript to run this app.</noscript>
<div id="root"></div>
</body>
```

아래에 스크린샷도 첨부합니다.
<img width="1326" alt="Screen Shot 2022-10-13 at 1 51 00 AM" src="https://user-images.githubusercontent.com/102022254/195403365-c88247b6-a581-412c-92f9-de95498f4f2d.png">

**Comment by storycraft** [comment]
아직 개발중 프론트엔드 테스트가 윈도우에서만 이뤄져서, 자바스크립트쪽 문제로 렌더링이 제대로 안되는 것 같습니다.

개발자도구에서 뜨는 자바스크립트 오류도 업로드 해주세요

**Comment by invu7** [comment]
> 아직 개발중 프론트엔드 테스트가 윈도우에서만 이뤄져서, 자바스크립트쪽 문제로 렌더링이 제대로 안되는 것 같습니다.
> 
> 개발자도구에서 뜨는 자바스크립트 오류도 업로드 해주세요


창 가운데 쪽에 뜨는 빨간색 (!) 아이콘 누르면 다음과 같이 나오는데, 이것을 말씀하신 것인지 모르겠네요.
혹시 더 필요하신 게 있으시면 말씀 주세요. 감사합니다.

<img width="1326" alt="Screen Shot 2022-10-13 at 2 02 23 PM" src="https://user-images.githubusercontent.com/102022254/195506206-a947bb4d-715e-4d9d-a82f-9b8408e57ba5.png">

**Comment by storycraft** [comment]
Optional chaining 지원이 안되는 것 같습니다. 환경이 어떻게 되시나요?

**Comment by invu7** [comment]
macOS Mojave (10.14.6) 입니다. 
최신은 아니지만 비교적 최신 OS인데, OS 문제일 수 있다니 이상하네요.

뭔가 security setting의 문제일 수도 있지 않을까요? 감사합니다.

**Comment by storycraft** [comment]
오류 위치와 해당 코드 부분도 업로드 가능할까요?

아이콘 오른쪽 역삼각형을 눌러 오류를 펼칠 수 있습니다

**Comment by invu7** [comment]
아래쪽 html 코드 말씀하시나요? (위쪽 빨간 (!) 부분은 이미 다 펼친 것입니다.)

html 코드는 그냥 제가 원글에서 말씀드린 "enable Javascript" 메세지를 보여주는 페이지이고,
펼쳐 보아도 오류 위치를 알려주는 별다른 표시가 없어서 그냥 저렇게만 올려드렸었는데,
지금 다시 전체 화면으로 펼쳐보았습니다. 맨 위 쪽에 script가 나오긴 하는데, 특별한 사항이 있을지 모르겠네요. 감사합니다.
<img width="1326" alt="Screen Shot 2022-10-13 at 3 54 35 PM" src="https://user-images.githubusercontent.com/102022254/195524909-0968913d-910d-44a5-ab03-57a11068bd0b.png">

**Comment by kreun** [comment]
Optional chaining
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Optional_chaining
자바스크립트 오류가 발생한 것 같습니다.
위의 문서에서 지원하는 브라우져 확인해보세요.
해당 문법이 비교적 최근에 나온 것이라, 사용하시는 브라우져가 2020년 이전이라면 동작하지 않을 수 있고,
브라우저 업데이트를 하면 해결 될 것 같습니다.

**Comment by invu7** [comment]
> Optional chaining https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Optional_chaining 자바스크립트 오류가 발생한 것 같습니다. 위의 문서에서 지원하는 브라우져 확인해보세요. 해당 문법이 비교적 최근에 나온 것이라, 사용하시는 브라우져가 2020년 이전이라면 동작하지 않을 수 있고, 브라우저 업데이트를 하면 해결 될 것 같습니다.

음, KiwiTalk 앱이 시스템 브라우저를 이용하는 건가요?
제가 현재 default browser로 사용 중인 브라우저는 Chrome인데, 알려주신 페이지에 의하면 version 80.xx 부터 가능하다고 하고,
제 현재 버젼은 106.0.5249.103 입니다.

MacOS에 원래 포함돼 있는 시스템 브라우저는 Safari인데, 안 쓴지 좀 오래되었지만 혹시나 싶어 확인해 보니 version이 12.xx 라고 나와서,
최신 버젼 14.xx으로 업데이트해서 해보았는데 (알려주신 페이지에서 안내된 지원 버젼은 13.1부터네요)

KiwiTalk을 실행하면 여전히 똑같은 에러가 나옵니다.
다르게 해 볼 수 있는 방법이 있을까요? 감사합니다.

**Comment by JellyBrick** [comment]
> > Optional chaining [developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Optional_chaining](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Optional_chaining) 자바스크립트 오류가 발생한 것 같습니다. 위의 문서에서 지원하는 브라우져 확인해보세요. 해당 문법이 비교적 최근에 나온 것이라, 사용하시는 브라우져가 2020년 이전이라면 동작하지 않을 수 있고, 브라우저 업데이트를 하면 해결 될 것 같습니다.
> 
> 음, KiwiTalk 앱이 시스템 브라우저를 이용하는 건가요? 제가 현재 default browser로 사용 중인 브라우저는 Chrome인데, 알려주신 페이지에 의하면 version 80.xx 부터 가능하다고 하고, 제 현재 버젼은 106.0.5249.103 입니다.
> 
> MacOS에 원래 포함돼 있는 시스템 브라우저는 Safari인데, 안 쓴지 좀 오래되었지만 혹시나 싶어 확인해 보니 version이 12.xx 라고 나와서, 최신 버젼 14.xx으로 업데이트해서 해보았는데 (알려주신 페이지에서 안내된 지원 버젼은 13.1부터네요)
> 
> KiwiTalk을 실행하면 여전히 똑같은 에러가 나옵니다. 다르게 해 볼 수 있는 방법이 있을까요? 감사합니다.

넵, KiwiTalk 앱은 시스템 브라우저 기반입니다.
해당 문제는 `babel` 타겟 버전을 낮춰서 해결해야 할 것 같네요
@KiwiTalk/frontend

**Comment by JellyBrick** [comment]
이제 KiwiTalk은 최소 Safari 13을 요구합니다.
