### ISSUE TITLE
반응형 크기 조절

### ISSUE THREAD

**Issue by Su-Yong** [KiwiTalk/KiwiTalk#129]
1. 화면 크기가 특정 크기 이상으로 커졌을 때 -> 오른쪽에 방 설정 및 참가자 목록 표시하기 (시선이 좌우로 왔다 갔다하는 문제가 (가독성 하락) 있었음)
2. 화면이 특정 크기 이상으로 작아졌을때 -> 채팅 내용만 보이기

**Comment by RanolP** [comment]
MVP 개발 이후 다양한 플랫폼에 대응하기 위해 반응형 디자인 작업을 진행하는 게 좋겠습니다. 현재 디자인 인력이 부족한 팀 특성상 다양한 해상도를 고려해 MVP를 개발하는 것이 어렵습니다. MVP 개발에 집중하기 위해 이 이슈는 닫아두겠습니다.
