### ISSUE TITLE
맥에서 설치했는데 로그인이 이루어지지 않습니다

### ISSUE THREAD

**Issue by lio8192** [KiwiTalk/KiwiTalk#1290]
안녕하세요.

키위톡 앱에서 로그인 후 기기 보안인증까지 진행했는데 로그인이 이루어지지 않고 소켓요청만 보내고 있네요

이 경우 어떻게 해야지 해결할 수 있을까요?

<img width="1445" alt="스크린샷 2022-10-22 오전 12 10 44" src="https://user-images.githubusercontent.com/32593843/197229378-7319e8f0-413e-4b7d-af65-e9176824167b.png">

**Comment by RanolP** [comment]
정상으로 알고 있습니다. 현재 프로젝트 구성 요소를 전반적으로 새로 작성하면서 기존 프론트엔드 구현을 버렸는데, 지금 로그인 이후 페이지 구현이 따로 안 되어 있을 겁니다.

**Comment by lio8192** [comment]
아.. 그렇군요 감사합니다!
