### ISSUE TITLE
CodeQL 브랜치 설정이 올바르지 않습니다.

### ISSUE THREAD

**Issue by RanolP** [KiwiTalk/KiwiTalk#1294]
## 문제 상황

현재 소스 코드를 보면 `branches: [ master ]`로 지정되어 있어 PR에서 CodeQL이 굴러가지 않는 모습을 볼 수 있습니다.

https://github.com/KiwiTalk/KiwiTalk/blob/c453a47dc70ad9fa305a1393e68f76df178efea2/.github/workflows/codeql-analysis.yml#L16-L19

## 해결 방안

해당 파일에서 브랜치 이름을 변경합니다.

**Comment by JellyBrick** [comment]
https://github.com/KiwiTalk/KiwiTalk/commit/1099cfc9366de6b32803d116c3b7159e955d141e
