### ISSUE TITLE
깃헙 저장소에 Discussions 탭 개설

### ISSUE THREAD

**Issue by wooseopkim** [KiwiTalk/KiwiTalk#1321]
### Describe the feature you would like to see.

질문 등 이슈가 아닌 사항에 대해 [tauri 등을 포함한 다수의 오픈 소스 프로젝트들이 Discussions 탭을 사용](https://github.com/tauri-apps/tauri/discussions)하는 것으로 알고 있습니다. 키위톡 또한 해당 기능 사용이 적절할까요? 아니라면 질문은 계속 이슈로 남기면 되는 것일까요?

### Describe the solution you'd like.

Discussions 탭 개설

**Comment by storycraft** [comment]
현재 기여, 개발에 대한 질문은 키위톡 디스코드에서 받고 있습니다. 디스코드 링크는 `readme.md`에 있습니다.

이미 디스코드에서 질문을 받고 있기 때문에 Github Discussions을 개설할경우 관리의 어려움이 있어 개설하지 않고 있습니다.
