### ISSUE TITLE
로그인후 반응이 없습니다.

### ISSUE THREAD

**Issue by dogedoge7** [KiwiTalk/KiwiTalk#1325]
안녕 하세요. 

wsl 환경으로 우분투에서 설치 하였습니다.

첫 로그인시 인증 코드 까지 다 받고 난후 로그인후 반응이 없습니다.

폰에서 카카오톡에 로그인 했다는 알람은 뜹니다.

계속 먹통 입니다.

무슨 문제 일까요?

![제목 없음](https://user-images.githubusercontent.com/67130972/200116690-78cd64d4-191b-42bc-a94f-6b0cf7432fb8.jpg)

**Comment by RanolP** [comment]
#1290 과 중복으로 추정됩니다. 중복이 아니라면 추가적인 설명과 함께 이슈를 다시 열어주십시오.
