### ISSUE TITLE
로그인이 되지 않습니다.

### ISSUE THREAD

**Issue by HexagonWin** [KiwiTalk/KiwiTalk#1408]
### Current behavior

`yarn dev`로 실행 후 KiwiTalk은 잘 실행되며, 이때 최초 로그인 시 비밀번호 입력 후 일회용/내PC 인증 버튼이 나오고, 내 PC로 인증을 누르면 모바일 클라이언트에는 인증번호가 나오며, KiwiTalk에는 번호 입력창이 나타납니다. 그러나, 이 때 번호 입력이 완료되는 즉시 초기 실행 화면으로 되돌아가며, 이후 모바일 클라이언트에서 해당 새 기기를 제거하기 전까지는 계속 로그인을 눌러도 화면에 변화가 없습니다.
제거시에는 초기와 같이 다시 인증을 진행하게 되고, 이후 동일합니다.

### Expected behavior

번호 입력 후 카카오톡 채팅방 등이 표시되며 기능을 이용할 수 있게 됩니다.

### Step to reproduce

1. `git clone https://github.com/KiwiTalk/KiwiTalk.git ./KiwiTalk && cd KiwiTalk`
2. `yarn`
3. `yarn dev`
4. 전화번호(이메일) / 비밀번호 입력
5. '내 PC 인증' 클릭
6. 인증코드 입력

### OS, or Other Environments

OS: Devuan GNU/Linux 4.0 chimaera (Debian 11 bullseye)
Node: v19.3.0 (Node repository)
```
$ node -v
v19.3.0
```
Using Development build: Yes

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all required informations.

**Comment by storycraft** [comment]
아직 로그인 부분을 제외한 부분은 구현중에 있습니다. #1267 에서 진행 상황을 확인하실수 있습니다.

**Comment by RanolP** [comment]
해당 PR이 머지되었으므로 이제 고정 해제하겠습니다.
