### ISSUE TITLE
개발에 참여하고 싶습니다, 관련 그룹이 있을까요?^^

### ISSUE THREAD

**Issue by songmeric** [KiwiTalk/KiwiTalk#1636]
카톡이나 디스코드 등 관련 그룹이 있다면 참여하고 싶습니다 ^^ 코드 커밋도 꾸준히 하려 합니다!

**Comment by JellyBrick** [comment]
README에 있는 discord 버튼을 누르시거나, 밑 링크를 사용하시면 됩니다.

https://discord.gg/vVs8WVY3y6
