### ISSUE TITLE
인증 후 로그인 시 아무 반응이 일어나지 않습니다.

### ISSUE THREAD

**Issue by asdfer-1234** [KiwiTalk/KiwiTalk#1743]
### Current behavior

인증번호를 입력하고 로그인 시 아무 반응도 일어나지 않습니다.
다만 공식 카카오톡 앱이 설치된 모바일 기기에서는 PC 로그인 알림이 뜨고 있습니다.

### Expected behavior

로그인이 됩니다.

### Step to reproduce

1. yarn dev로 키위톡을 실행합니다.
2. 이메일과 비밀번호를 입력합니다.
3. 모바일 기기에서 기기 인증을 해줍니다.
4. 로그인 버튼을 누릅니다.

### OS, or Other Environments

OS: Arch Linux
버전: dc1318bf4a8e8270a7ed7170e804d2e46b11686b
(git log)

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all required informations.

**Comment by hajunwon** [comment]
비번이 틀렸네요

**Comment by asdfer-1234** [comment]
에러 코드 도큐멘테이션이 있나요?

**Comment by storycraft** [comment]
기기등록은 성공적으로 되지만 이후 로그인이 안되는건가요?

**Comment by hajunwon** [comment]
> 

https://github.com/KiwiTalk/loco.rs/issues/11

**Comment by asdfer-1234** [comment]
에러코드 12번은 맨 처음에 제가 비밀번호를 잘못 입력해서 떴던게 비밀번호를 맞는 걸로 바꾸고 나서 로그인 버튼을 눌렀을 때 붉은 글씨가 남아있는 걸 제가 읽어서 이슈 수정 전처럼 버그를 제보한 것 같습니다.

로그인 버튼 클릭 시 모바일 기기에 PC 로그인 알림이 뜹니다. 그러나 키위톡 클라이언트에서는 변화가 없네요.

**Comment by JellyBrick** [comment]
25553acad71cc875f163088df4f482b3f367a176 에서 수정
