### ISSUE TITLE
유저별 콘픽 저장소 구현

### ISSUE THREAD

**Issue by storycraft** [KiwiTalk/KiwiTalk#1955]
### 새로운 기능이나 개선사항을 작성해 주세요.

백엔드와 프론트엔드에서 사용 가능한 유저별 설정 저장소 api를 구현합니다.

### 개선사항에 대한 더 자세한 내용을 기술해 주세요.

임의의 key, value 짝을 저장할 수 있어야 합니다. 각 채팅방 설정, 개인 설정 등이 저장됩니다.

구현에 redb를 사용할 수 있습니다.

**Comment by RanolP** [comment]
설정은 v2 개발 때 스쿼드로 갈게요. 당장은 이슈 닫아두겠습니다.
