### ISSUE TITLE
채팅창 구현

### ISSUE THREAD

**Issue by storycraft** [KiwiTalk/KiwiTalk#1956]
### Describe the feature you would like to see.

채팅창을 구현합니다.

**선행되어야 하는 이슈**
* [x] #1958
* [ ] #1957

### Describe the solution you'd like.

채팅 입력 컴포넌트, 채팅창 배경과 채팅들이 배치 될 수 있는 컴포넌트입니다.

**Comment by RanolP** [comment]
스쿼드 형태로 쪼개서 진행하기 위해 이 이슈는 닫겠습니다
