### ISSUE TITLE
일반채팅에서 답장 시 이미 퇴장한 사람이름이 undefined로 보여짐

### ISSUE THREAD

**Issue by KeliPhy** [KiwiTalk/KiwiTalk#200]
일반채팅방에서 퇴장 후 채팅을 불러오면 답장에서 이름이 undefined로 보여짐

![exam](https://user-images.githubusercontent.com/63758483/108662314-67205c80-7511-11eb-814a-937dd91e6f2e.png)

**Comment by nunnu1028** [comment]
여기 커밋이 요즘따라 없네요.

**Comment by JellyBrick** [comment]
@nunnu1028 refactoring 버전에서도 해당 문제가 발생하나요??

**Comment by nunnu1028** [comment]
@JellyBrick 제가 쓴 이슈가 아니라서 모르겠네요 키위톡 안써본지도 오래된터라

**Comment by JellyBrick** [comment]
해당 문제가 아직도 발생하나요?

**Comment by KeliPhy** [comment]
해결되었으므로 이슈를 닫습니다.
