### ISSUE TITLE
[SOLVED] 우분투에서 빌드시 키위톡이 빈 화면만 출력합니다.

### ISSUE THREAD

**Issue by lidarbtc** [KiwiTalk/KiwiTalk#2001]
### 현재 작동 방식

![스크린샷 2023-10-04 17-36-22](https://github.com/KiwiTalk/KiwiTalk/assets/97009593/8ac6ae55-f994-4566-b130-56adf9911c76)
해당 스크린샷 처럼 빈 화면만 출력합니다.

해결법:
```bash
export WEBKIT_DISABLE_COMPOSITING_MODE=1
```
해당 명령어를 입력한 후 빌드 시 정상적으로 작동합니다.

### 재현 단계

1. 우분투에서 빌드를 합니다.

### 운영체제, 실행환경 정보

OS: Ubuntu 22.04

### 중복되는 이슈가 있나요?

- [X] 이슈 제출전 중복되는 이슈가 없는지 확인 했습니다.
- [X] 필요한 정보들을 모두 작성했습니다.

**Comment by storycraft** [comment]
https://github.com/tauri-apps/tauri/issues/5143
