### ISSUE TITLE
설정 창 구현

### ISSUE THREAD

**Issue by JellyBrick** [KiwiTalk/KiwiTalk#2009]
### 새로운 기능이나 개선사항을 작성해 주세요.

설정 창을 구현합니다.

#### 선행되어야 하는 작업

- 설정 창 관련 디자인이 필요합니다.

### 개선사항에 대한 더 자세한 내용을 기술해 주세요.

설정 입력, 체크 박스 등 간단한 설정들이 배치될 수 있는 컴포넌트입니다.

**Comment by RanolP** [comment]
설정창 구현은 v2 스쿼드로 미루고, 닫아두겠습니다.
