### ISSUE TITLE
친구/채널/메세지 목록이 뜨지 않고 설정버튼, 잠금버튼 모두 동작하지 않음

### ISSUE THREAD

**Issue by jclab-joseph** [KiwiTalk/KiwiTalk#2023]
### 현재 작동 방식

친구,채널,일반채팅,오픈채팅 모두 0으로 뜨며
잠금버튼, 설정버튼 눌러도 아무 동작하지 않습니다.

![image](https://github.com/KiwiTalk/KiwiTalk/assets/88625531/5d53c07c-3dcb-48d1-b110-35f4a5c54243)

### 재현 단계

1. kiwi-talk_0.1.2_amd64.AppImage 을 실행합니다. (데이터 디렉터리 없는 상태)
2. 스마트폰에서 인증하여 PC 을 등록합니다.
3. 로그인을 합니다. 

### 운영체제, 실행환경 정보

OS: 22.04.1 LTS (Jammy Jellyfish) / X86_64
Using Development build: No

### 중복되는 이슈가 있나요?

- [X] 이슈 제출전 중복되는 이슈가 없는지 확인 했습니다.
- [X] 필요한 정보들을 모두 작성했습니다.

**Comment by JellyBrick** [comment]
Related to #2018

**Comment by jclab-joseph** [comment]
@JellyBrick 현재 어떤 부분들이 구현되었는지에 대한 리스트가 있나요?
현재는 로그인 외에는 아무것도 안되는게 맞는건가요?

**Comment by JellyBrick** [comment]
> @JellyBrick 현재 어떤 부분들이 구현되었는지에 대한 리스트가 있나요? 현재는 로그인 외에는 아무것도 안되는게 맞는건가요?

넵, 인증, 로그인, 채팅 알림 외 기능은 아직 재작성 중입니다. (#2018, #1)
