### ISSUE TITLE
ARM 기기에서 NW.js를 실행할 수 없음

### ISSUE THREAD

**Issue by JellyBrick** [KiwiTalk/KiwiTalk#264]
- `nw-builder` 내부 로직 문제로 보임

- `Ubuntu (Linux)` (ARMv7, ARMv8): NW.js 바이너리 다운로드 불가

- `Apple Silicon (M1)`: 로제타v2로 실행시 `osx32`로 인식되어 실행 불가. `osx64` 바이너리 사용시  로제타v2 통해 실행 가능.

https://github.com/KiwiTalk/nw-builder-reforged

**Comment by RanolP** [comment]
#1171 (Rewriting backend and possibly frontend)이 머지될 경우, NW.js를 더이상 사용하지 않게 됩니다.
Tauri의 경우 현재 aarch64를 이미 지원하고 있는 것으로 알고 있습니다. 또, 최근 Tauri 디스코드에서 mobile 채널이 활발해짐에 따라 부족한 지원이 있더라도 경우 빠르게 개선될 것으로 보입니다.
