### ISSUE TITLE
의존성 브랜치 분리

### ISSUE THREAD

**Issue by JellyBrick** [KiwiTalk/KiwiTalk#280]
## 현재

dependabot 커밋이 지나치게 많아, 중요한 커밋 내역을 볼 수 없음

## 해결 방안

- 의존성 업데이트 전용 브랜치 분리
- 스쿼시 머지 사용하여 병합

### 예상되는 문제

- git 충돌 (기존에는 dependabot이 자동 rebase 해줬음)

**Comment by dayo05** [comment]
dependabot을 항상 켜두는게 아니라 잠깐잠깐 켜놓는다면 브랜치 분리와 유사하게 동작 가능하지 않을까요?

**Comment by JellyBrick** [comment]
- [x] dependabot에서 renovate로 교체
