### ISSUE TITLE
빈 메시지가 보내집니다

### ISSUE THREAD

**Issue by CodePsy-2001** [KiwiTalk/KiwiTalk#634]
키위톡 실행 후 아무 채팅방이나 들어가서 메시지 보내기 버튼(비행기 모양)을 누르면, 빈 메시지가 전송됩니다.

**Comment by JellyBrick** [comment]
프론트엔드 코드 리팩토링 및 백엔드 코드 교체로 인해 더 이상 발생하지 않는 이슈가 되었으므로, close 하겠습니다.
