### ISSUE TITLE
키위톡 클라 개발에 기여하고 싶습니다.

### ISSUE THREAD

**Issue by CodePsy-2001** [KiwiTalk/KiwiTalk#635]
웹 프로그램 디자인에 관심을 가지고 있는 초보 개발자입니다. 재직중인 회사에서 풀스택 경험이 있습니다. (몽고DB CRUD 구현, 미들웨어 사용, 의존성 주입, 리액트 아토믹 디자인 개발 등) 아직 백엔드 경험은 부족하지만, 리액트 클라이언트의 디자인 다듬는 일을 도와드리고 싶습니다. 관련해서 필요한 작업이 있을까요? 어떤 방식으로 도와드리면 될까요? 오픈소스 참여 경험이 전무해서 양해 부탁드립니다. (협업 경험도 거의 없습니다. 재직중인 회사의 모든 개발은 제가 담당하고 있습니다)

**Comment by CodePsy-2001** [comment]
채팅방 배경색 변경, (라인 PC 버전처럼) 버튼 클릭으로 메뉴창 띄우는 여부 결정하기, 필요한 곳에만 부분적으로 아토믹 디자인 적용 (다크모드 적용 등의 장점이 있습니다) 등등의 개선안을 생각해봤습니다. 또는 리액트의 장점(개방적인 웹앱)을 십분 활용해서 업무 자동화에 사용할 수 있는 추가 기능 같은 걸 제공해주는 방식도 좋을 것 같아요. 카카오톡 API를 사용해서 기능이 달린 말풍선 같은 걸 쏠수 있는데, 그걸 응용해봐도 좋구요.

**Comment by JellyBrick** [comment]
기여는 항상 환영입니다!
~~`v4` 브랜치에 PR 넣어주시면 리뷰 후 머지토록 하겠습니다.~~
`dev` 브랜치에 PR 넣어주시면 리뷰 후 머지토록 하겠습니다!

**Comment by CodePsy-2001** [comment]
감사합니다! 시니어 분들과 같이 작업해보는 게 처음인데 코드리뷰 많이 해주시면 감사하겠습니다. 조그만한 기능 추가 하나 해보겠습니다.

**Comment by greenstar1151** [comment]
장기적으로 키위톡 프로젝트에 관심이 있으시다면 전체적인 디자인에 대해 함께 논의를 나눠볼 수 있을 것 같습니다. 현재는 제가 목업 디자인을 담당하고 있는데, 다양한 아이디어는 항상 환영합니다! 기여 감사드립니다.

![image](https://user-images.githubusercontent.com/39073901/132298078-f02d32be-a43f-4a60-8e94-ec7f5106ed9a.png)

**Comment by MingiHongHub** [comment]
안녕하세요! 제가 해외거주중인데 카카오톡을 쓰면서 한국에 계신 부모님과 보이스톡이나 페이스톡을할때 자꾸 끈김현상이 발생해서 그 버그를 좀 개선해보려고 카카오톡 소스코드를 찾는중에 키위톡에 관심이 가게 되었습니다. 혹시 키위톡에서 보이스톡이나 페이스톡을 사용할때 사용되는 프로토콜이 카카오톡에 사용되는 프로토콜과 같다면은 그 버그를 이 키위톡에서 잡으면 될것같다는 아이디어가 생겼는데, 키위톡에 같은 프로토콜이 사용되나요?

버그에 대해 정확히 말하자면은 제가 부모님께 전화를 드리면 자주 끈김현상이 발생하지만, 부모님께서 한국에서 저한테 전화를 주면은 끈김현상이 발생하지 않더라고요. 이것엔 꼭 무슨이유가 있을것 같은데 이 키위톡 프로젝트를 통해서 이점이 개선됬으면 좋겠네요.

**Comment by RanolP** [comment]
KiwiTalk 개발과 무관한 이슈라 닫겠습니다. 개발에 참여하고 싶으신 의사가 여전히 남아계시다면 [Discord](https://discord.gg/n3eHuNuRYf)를 통해 소통해주시면 감사하겠습니다.
