### ISSUE TITLE
톡서랍 지원

### ISSUE THREAD

**Issue by JellyBrick** [KiwiTalk/KiwiTalk#64]

**Comment by nnnlog** [comment]
3.2.1 버전 기준으로 톡서랍 호스트가 기존의 `drawer-api.kakao.com` 가 아닌 `talk-pilsner.kakao.com` 로 변경됨에 따라 Authorization에 `MALDIVE `를 붙이지 않습니다.

**Comment by RanolP** [comment]
톡서랍은 당장 구현하기엔 복잡한 기능이므로 일단 이슈를 닫아두겠습니다. 추후 고도화 작업 시 스쿼드로 진행할 수 있습니다.
