### ISSUE TITLE
`react-router-dom` v6 사용시 오류 발생

### ISSUE THREAD

**Issue by pikokr** [KiwiTalk/KiwiTalk#773]
dev 브랜치 이용해서 실행해보니 코드가 react-router-dom v6 버전에 맞지 않아 오류가 생기네요.

그리고 웹팩 설정에도 문제가 생겼습니다.

**Comment by JellyBrick** [comment]
- 임시방편으로, react-router-dom 버전을 v5로 낮췄습니다.
- webpack-dev-server 관련 오류 해결 완료되었습니다.

**Comment by JellyBrick** [comment]
https://github.com/KiwiTalk/KiwiTalk/commit/fe2189008755bcc9953e806e3eec640c6cacfaaf

**Comment by JellyBrick** [comment]
#1171
