### ISSUE TITLE
카카오톡 운영정책 변경

### ISSUE THREAD

**Issue by DeltaLaboratory** [KiwiTalk/KiwiTalk#786]
[2021년 12월 7일부터 적용되는 개정된 운영정책](http://kko.to/KQULO7Z4B)에 의하면,

- 역분석 코드를 이용하여 카카오톡과 표현이 실질적으로 유사한 프로그램을 개발·제작하는 행위 [P37L5]
- 프로그램코드 역분석을 통하여 얻은 정보를 제 3 자에게 제공·공개하는 행위 [P37L4]
- 카카오가 허용하지 않은 비정상적인 프로그램 등을 이용하여 카카오톡의 프로토콜·API 등을 부정하게
호출하는 행위 [P37L9]
등을 금지하고 있습니다.
상기 운영정책에 따르면, 이 클라이언트는 카카오 운영정책에 위배됩니다.
이에 따른 대책이 있으시거나, 이 클라이언트를 삭제할 의향이 있으십니까?

**Comment by JellyBrick** [comment]
[P37L5], [P37L4]. 해당 프로그램은 역분석이 필요한 부분이 포함되어있지 않습니다.
[P37L9]. README에 명시되어있듯, 해당 클라이언트는 카카오톡이 지원되지 않는 기기 (예: `Ubuntu`, `Arch Linux`)를 위해 연구 목적으로 만들어졌으며, 해당 클라이언트를 사용함으로써 발생하는 모든 책임은 사용자에게 있습니다.

따라서 키위톡 팀의 방침은 현재와 동일합니다.

**Comment by DeltaLaboratory** [comment]
> * [P37L5], [P37L4]. 해당 프로그램은 역분석이 필요한 부분이 포함되어있지 않습니다.
> * [P37L9]. README에 명시되어있듯, 해당 클라이언트는 카카오톡이 지원되지 않는 기기 (예: `Ubuntu`, `Arch Linux`)를 위해 연구 목적으로 만들어진 클린룸 구현입니다. 해당 클라이언트를 사용함으로써 발생하는 모든 책임은 사용자에게 있습니다.
> 
> 따라서 키위톡 팀의 방침은 현재와 동일합니다.

https://github.com/KiwiTalk/KiwiTalk/blob/master/src/constants/Configs.ts
XVC 키는 어떻게 구하셨나요?

**Comment by JellyBrick** [comment]
> > * [P37L5], [P37L4]. 해당 프로그램은 역분석이 필요한 부분이 포함되어있지 않습니다.
> > * [P37L9]. README에 명시되어있듯, 해당 클라이언트는 카카오톡이 지원되지 않는 기기 (예: `Ubuntu`, `Arch Linux`)를 위해 연구 목적으로 만들어진 클린룸 구현입니다. 해당 클라이언트를 사용함으로써 발생하는 모든 책임은 사용자에게 있습니다.
> > 
> > 따라서 키위톡 팀의 방침은 현재와 동일합니다.
> 
> [`master`/src/constants/Configs.ts](https://github.com/KiwiTalk/KiwiTalk/blob/master/src/constants/Configs.ts?rgh-link-date=2021-11-13T16%3A45%3A42Z) XVC 키는 어떻게 구하셨나요? [`master`/src/constants/AuthConstants.ts](https://github.com/KiwiTalk/KiwiTalk/blob/master/src/constants/AuthConstants.ts?rgh-link-date=2021-11-13T16%3A45%3A42Z) 서버측 에러코드를 어떻게 클린룸 구현으로 알 수 있나요?

1. 정확한 방법은 알려드릴 수 없으나, 상기된 `리버싱`과 같은 방법을 사용하지는 않았습니다.
2. 직접 에러를 발생시켜보는 방법으로 추측한 것입니다.
